// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test2.proto

package com.zhang.sqone.bean;

public final class Test2 {
  private Test2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqTest22OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string ac = 1;
    /**
     * <code>optional string ac = 1;</code>
     *
     * <pre>
     *请求标识
     * </pre>
     */
    boolean hasAc();
    /**
     * <code>optional string ac = 1;</code>
     *
     * <pre>
     *请求标识
     * </pre>
     */
    java.lang.String getAc();
    /**
     * <code>optional string ac = 1;</code>
     *
     * <pre>
     *请求标识
     * </pre>
     */
    com.google.protobuf.ByteString
        getAcBytes();

    // optional string id = 2;
    /**
     * <code>optional string id = 2;</code>
     *
     * <pre>
     *ID
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional string id = 2;</code>
     *
     * <pre>
     *ID
     * </pre>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 2;</code>
     *
     * <pre>
     *ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // optional string stu = 3;
    /**
     * <code>optional string stu = 3;</code>
     *
     * <pre>
     *请求返回标识
     * </pre>
     */
    boolean hasStu();
    /**
     * <code>optional string stu = 3;</code>
     *
     * <pre>
     *请求返回标识
     * </pre>
     */
    java.lang.String getStu();
    /**
     * <code>optional string stu = 3;</code>
     *
     * <pre>
     *请求返回标识
     * </pre>
     */
    com.google.protobuf.ByteString
        getStuBytes();

    // optional string scd = 4;
    /**
     * <code>optional string scd = 4;</code>
     *
     * <pre>
     *请求结果标识
     * </pre>
     */
    boolean hasScd();
    /**
     * <code>optional string scd = 4;</code>
     *
     * <pre>
     *请求结果标识
     * </pre>
     */
    java.lang.String getScd();
    /**
     * <code>optional string scd = 4;</code>
     *
     * <pre>
     *请求结果标识
     * </pre>
     */
    com.google.protobuf.ByteString
        getScdBytes();

    // optional string msg = 7;
    /**
     * <code>optional string msg = 7;</code>
     *
     * <pre>
     *请求结果消息
     * </pre>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 7;</code>
     *
     * <pre>
     *请求结果消息
     * </pre>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 7;</code>
     *
     * <pre>
     *请求结果消息
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    // optional string sid = 8;
    /**
     * <code>optional string sid = 8;</code>
     *
     * <pre>
     *请求的用户sid
     * </pre>
     */
    boolean hasSid();
    /**
     * <code>optional string sid = 8;</code>
     *
     * <pre>
     *请求的用户sid
     * </pre>
     */
    java.lang.String getSid();
    /**
     * <code>optional string sid = 8;</code>
     *
     * <pre>
     *请求的用户sid
     * </pre>
     */
    com.google.protobuf.ByteString
        getSidBytes();

    // optional string dcode = 11;
    /**
     * <code>optional string dcode = 11;</code>
     *
     * <pre>
     *科室code
     * </pre>
     */
    boolean hasDcode();
    /**
     * <code>optional string dcode = 11;</code>
     *
     * <pre>
     *科室code
     * </pre>
     */
    java.lang.String getDcode();
    /**
     * <code>optional string dcode = 11;</code>
     *
     * <pre>
     *科室code
     * </pre>
     */
    com.google.protobuf.ByteString
        getDcodeBytes();

    // optional string p = 12;
    /**
     * <code>optional string p = 12;</code>
     *
     * <pre>
     *当前页数
     * </pre>
     */
    boolean hasP();
    /**
     * <code>optional string p = 12;</code>
     *
     * <pre>
     *当前页数
     * </pre>
     */
    java.lang.String getP();
    /**
     * <code>optional string p = 12;</code>
     *
     * <pre>
     *当前页数
     * </pre>
     */
    com.google.protobuf.ByteString
        getPBytes();

    // optional .ReqTest22.Test22Map a = 13;
    /**
     * <code>optional .ReqTest22.Test22Map a = 13;</code>
     *
     * <pre>
     *对象1
     * </pre>
     */
    boolean hasA();
    /**
     * <code>optional .ReqTest22.Test22Map a = 13;</code>
     *
     * <pre>
     *对象1
     * </pre>
     */
    com.zhang.sqone.bean.Test2.ReqTest22.Test22Map getA();
    /**
     * <code>optional .ReqTest22.Test22Map a = 13;</code>
     *
     * <pre>
     *对象1
     * </pre>
     */
    com.zhang.sqone.bean.Test2.ReqTest22.Test22MapOrBuilder getAOrBuilder();
  }
  /**
   * Protobuf type {@code ReqTest22}
   *
   * <pre>
   *科室工作
   * </pre>
   */
  public static final class ReqTest22 extends
      com.google.protobuf.GeneratedMessage
      implements ReqTest22OrBuilder {
    // Use ReqTest22.newBuilder() to construct.
    private ReqTest22(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqTest22(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqTest22 defaultInstance;
    public static ReqTest22 getDefaultInstance() {
      return defaultInstance;
    }

    public ReqTest22 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqTest22(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              ac_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              id_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              stu_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              scd_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000010;
              msg_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000020;
              sid_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000040;
              dcode_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000080;
              p_ = input.readBytes();
              break;
            }
            case 106: {
              com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.Builder subBuilder = null;
              if (((bitField0_ & 0x00000100) == 0x00000100)) {
                subBuilder = a_.toBuilder();
              }
              a_ = input.readMessage(com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(a_);
                a_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000100;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhang.sqone.bean.Test2.internal_static_ReqTest22_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhang.sqone.bean.Test2.internal_static_ReqTest22_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhang.sqone.bean.Test2.ReqTest22.class, com.zhang.sqone.bean.Test2.ReqTest22.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqTest22> PARSER =
        new com.google.protobuf.AbstractParser<ReqTest22>() {
      public ReqTest22 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqTest22(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqTest22> getParserForType() {
      return PARSER;
    }

    public interface Test22MapOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string xm = 1;
      /**
       * <code>optional string xm = 1;</code>
       *
       * <pre>
       *姓名
       * </pre>
       */
      boolean hasXm();
      /**
       * <code>optional string xm = 1;</code>
       *
       * <pre>
       *姓名
       * </pre>
       */
      java.lang.String getXm();
      /**
       * <code>optional string xm = 1;</code>
       *
       * <pre>
       *姓名
       * </pre>
       */
      com.google.protobuf.ByteString
          getXmBytes();

      // optional string nl = 2;
      /**
       * <code>optional string nl = 2;</code>
       *
       * <pre>
       *年龄
       * </pre>
       */
      boolean hasNl();
      /**
       * <code>optional string nl = 2;</code>
       *
       * <pre>
       *年龄
       * </pre>
       */
      java.lang.String getNl();
      /**
       * <code>optional string nl = 2;</code>
       *
       * <pre>
       *年龄
       * </pre>
       */
      com.google.protobuf.ByteString
          getNlBytes();
    }
    /**
     * Protobuf type {@code ReqTest22.Test22Map}
     */
    public static final class Test22Map extends
        com.google.protobuf.GeneratedMessage
        implements Test22MapOrBuilder {
      // Use Test22Map.newBuilder() to construct.
      private Test22Map(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Test22Map(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Test22Map defaultInstance;
      public static Test22Map getDefaultInstance() {
        return defaultInstance;
      }

      public Test22Map getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Test22Map(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                xm_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                nl_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhang.sqone.bean.Test2.internal_static_ReqTest22_Test22Map_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhang.sqone.bean.Test2.internal_static_ReqTest22_Test22Map_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.class, com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.Builder.class);
      }

      public static com.google.protobuf.Parser<Test22Map> PARSER =
          new com.google.protobuf.AbstractParser<Test22Map>() {
        public Test22Map parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Test22Map(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Test22Map> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional string xm = 1;
      public static final int XM_FIELD_NUMBER = 1;
      private java.lang.Object xm_;
      /**
       * <code>optional string xm = 1;</code>
       *
       * <pre>
       *姓名
       * </pre>
       */
      public boolean hasXm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string xm = 1;</code>
       *
       * <pre>
       *姓名
       * </pre>
       */
      public java.lang.String getXm() {
        java.lang.Object ref = xm_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            xm_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string xm = 1;</code>
       *
       * <pre>
       *姓名
       * </pre>
       */
      public com.google.protobuf.ByteString
          getXmBytes() {
        java.lang.Object ref = xm_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          xm_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string nl = 2;
      public static final int NL_FIELD_NUMBER = 2;
      private java.lang.Object nl_;
      /**
       * <code>optional string nl = 2;</code>
       *
       * <pre>
       *年龄
       * </pre>
       */
      public boolean hasNl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string nl = 2;</code>
       *
       * <pre>
       *年龄
       * </pre>
       */
      public java.lang.String getNl() {
        java.lang.Object ref = nl_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nl_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string nl = 2;</code>
       *
       * <pre>
       *年龄
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNlBytes() {
        java.lang.Object ref = nl_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        xm_ = "";
        nl_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getXmBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getNlBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getXmBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getNlBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.zhang.sqone.bean.Test2.ReqTest22.Test22Map parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.zhang.sqone.bean.Test2.ReqTest22.Test22Map parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.zhang.sqone.bean.Test2.ReqTest22.Test22Map parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.zhang.sqone.bean.Test2.ReqTest22.Test22Map parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.zhang.sqone.bean.Test2.ReqTest22.Test22Map parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.zhang.sqone.bean.Test2.ReqTest22.Test22Map parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.zhang.sqone.bean.Test2.ReqTest22.Test22Map parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.zhang.sqone.bean.Test2.ReqTest22.Test22Map parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.zhang.sqone.bean.Test2.ReqTest22.Test22Map parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.zhang.sqone.bean.Test2.ReqTest22.Test22Map parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.zhang.sqone.bean.Test2.ReqTest22.Test22Map prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ReqTest22.Test22Map}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.zhang.sqone.bean.Test2.ReqTest22.Test22MapOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.zhang.sqone.bean.Test2.internal_static_ReqTest22_Test22Map_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.zhang.sqone.bean.Test2.internal_static_ReqTest22_Test22Map_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.class, com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.Builder.class);
        }

        // Construct using com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          xm_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          nl_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.zhang.sqone.bean.Test2.internal_static_ReqTest22_Test22Map_descriptor;
        }

        public com.zhang.sqone.bean.Test2.ReqTest22.Test22Map getDefaultInstanceForType() {
          return com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.getDefaultInstance();
        }

        public com.zhang.sqone.bean.Test2.ReqTest22.Test22Map build() {
          com.zhang.sqone.bean.Test2.ReqTest22.Test22Map result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.zhang.sqone.bean.Test2.ReqTest22.Test22Map buildPartial() {
          com.zhang.sqone.bean.Test2.ReqTest22.Test22Map result = new com.zhang.sqone.bean.Test2.ReqTest22.Test22Map(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.xm_ = xm_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.nl_ = nl_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.zhang.sqone.bean.Test2.ReqTest22.Test22Map) {
            return mergeFrom((com.zhang.sqone.bean.Test2.ReqTest22.Test22Map)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.zhang.sqone.bean.Test2.ReqTest22.Test22Map other) {
          if (other == com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.getDefaultInstance()) return this;
          if (other.hasXm()) {
            bitField0_ |= 0x00000001;
            xm_ = other.xm_;
            onChanged();
          }
          if (other.hasNl()) {
            bitField0_ |= 0x00000002;
            nl_ = other.nl_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.zhang.sqone.bean.Test2.ReqTest22.Test22Map parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.zhang.sqone.bean.Test2.ReqTest22.Test22Map) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string xm = 1;
        private java.lang.Object xm_ = "";
        /**
         * <code>optional string xm = 1;</code>
         *
         * <pre>
         *姓名
         * </pre>
         */
        public boolean hasXm() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string xm = 1;</code>
         *
         * <pre>
         *姓名
         * </pre>
         */
        public java.lang.String getXm() {
          java.lang.Object ref = xm_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            xm_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string xm = 1;</code>
         *
         * <pre>
         *姓名
         * </pre>
         */
        public com.google.protobuf.ByteString
            getXmBytes() {
          java.lang.Object ref = xm_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            xm_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string xm = 1;</code>
         *
         * <pre>
         *姓名
         * </pre>
         */
        public Builder setXm(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          xm_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string xm = 1;</code>
         *
         * <pre>
         *姓名
         * </pre>
         */
        public Builder clearXm() {
          bitField0_ = (bitField0_ & ~0x00000001);
          xm_ = getDefaultInstance().getXm();
          onChanged();
          return this;
        }
        /**
         * <code>optional string xm = 1;</code>
         *
         * <pre>
         *姓名
         * </pre>
         */
        public Builder setXmBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          xm_ = value;
          onChanged();
          return this;
        }

        // optional string nl = 2;
        private java.lang.Object nl_ = "";
        /**
         * <code>optional string nl = 2;</code>
         *
         * <pre>
         *年龄
         * </pre>
         */
        public boolean hasNl() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string nl = 2;</code>
         *
         * <pre>
         *年龄
         * </pre>
         */
        public java.lang.String getNl() {
          java.lang.Object ref = nl_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            nl_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string nl = 2;</code>
         *
         * <pre>
         *年龄
         * </pre>
         */
        public com.google.protobuf.ByteString
            getNlBytes() {
          java.lang.Object ref = nl_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            nl_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string nl = 2;</code>
         *
         * <pre>
         *年龄
         * </pre>
         */
        public Builder setNl(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          nl_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string nl = 2;</code>
         *
         * <pre>
         *年龄
         * </pre>
         */
        public Builder clearNl() {
          bitField0_ = (bitField0_ & ~0x00000002);
          nl_ = getDefaultInstance().getNl();
          onChanged();
          return this;
        }
        /**
         * <code>optional string nl = 2;</code>
         *
         * <pre>
         *年龄
         * </pre>
         */
        public Builder setNlBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          nl_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ReqTest22.Test22Map)
      }

      static {
        defaultInstance = new Test22Map(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ReqTest22.Test22Map)
    }

    private int bitField0_;
    // optional string ac = 1;
    public static final int AC_FIELD_NUMBER = 1;
    private java.lang.Object ac_;
    /**
     * <code>optional string ac = 1;</code>
     *
     * <pre>
     *请求标识
     * </pre>
     */
    public boolean hasAc() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string ac = 1;</code>
     *
     * <pre>
     *请求标识
     * </pre>
     */
    public java.lang.String getAc() {
      java.lang.Object ref = ac_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ac_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ac = 1;</code>
     *
     * <pre>
     *请求标识
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAcBytes() {
      java.lang.Object ref = ac_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 2;</code>
     *
     * <pre>
     *ID
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string id = 2;</code>
     *
     * <pre>
     *ID
     * </pre>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 2;</code>
     *
     * <pre>
     *ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string stu = 3;
    public static final int STU_FIELD_NUMBER = 3;
    private java.lang.Object stu_;
    /**
     * <code>optional string stu = 3;</code>
     *
     * <pre>
     *请求返回标识
     * </pre>
     */
    public boolean hasStu() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string stu = 3;</code>
     *
     * <pre>
     *请求返回标识
     * </pre>
     */
    public java.lang.String getStu() {
      java.lang.Object ref = stu_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stu_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stu = 3;</code>
     *
     * <pre>
     *请求返回标识
     * </pre>
     */
    public com.google.protobuf.ByteString
        getStuBytes() {
      java.lang.Object ref = stu_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stu_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string scd = 4;
    public static final int SCD_FIELD_NUMBER = 4;
    private java.lang.Object scd_;
    /**
     * <code>optional string scd = 4;</code>
     *
     * <pre>
     *请求结果标识
     * </pre>
     */
    public boolean hasScd() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string scd = 4;</code>
     *
     * <pre>
     *请求结果标识
     * </pre>
     */
    public java.lang.String getScd() {
      java.lang.Object ref = scd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          scd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string scd = 4;</code>
     *
     * <pre>
     *请求结果标识
     * </pre>
     */
    public com.google.protobuf.ByteString
        getScdBytes() {
      java.lang.Object ref = scd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string msg = 7;
    public static final int MSG_FIELD_NUMBER = 7;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 7;</code>
     *
     * <pre>
     *请求结果消息
     * </pre>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string msg = 7;</code>
     *
     * <pre>
     *请求结果消息
     * </pre>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 7;</code>
     *
     * <pre>
     *请求结果消息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string sid = 8;
    public static final int SID_FIELD_NUMBER = 8;
    private java.lang.Object sid_;
    /**
     * <code>optional string sid = 8;</code>
     *
     * <pre>
     *请求的用户sid
     * </pre>
     */
    public boolean hasSid() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string sid = 8;</code>
     *
     * <pre>
     *请求的用户sid
     * </pre>
     */
    public java.lang.String getSid() {
      java.lang.Object ref = sid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sid = 8;</code>
     *
     * <pre>
     *请求的用户sid
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSidBytes() {
      java.lang.Object ref = sid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string dcode = 11;
    public static final int DCODE_FIELD_NUMBER = 11;
    private java.lang.Object dcode_;
    /**
     * <code>optional string dcode = 11;</code>
     *
     * <pre>
     *科室code
     * </pre>
     */
    public boolean hasDcode() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string dcode = 11;</code>
     *
     * <pre>
     *科室code
     * </pre>
     */
    public java.lang.String getDcode() {
      java.lang.Object ref = dcode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dcode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dcode = 11;</code>
     *
     * <pre>
     *科室code
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDcodeBytes() {
      java.lang.Object ref = dcode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string p = 12;
    public static final int P_FIELD_NUMBER = 12;
    private java.lang.Object p_;
    /**
     * <code>optional string p = 12;</code>
     *
     * <pre>
     *当前页数
     * </pre>
     */
    public boolean hasP() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string p = 12;</code>
     *
     * <pre>
     *当前页数
     * </pre>
     */
    public java.lang.String getP() {
      java.lang.Object ref = p_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          p_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string p = 12;</code>
     *
     * <pre>
     *当前页数
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPBytes() {
      java.lang.Object ref = p_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        p_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .ReqTest22.Test22Map a = 13;
    public static final int A_FIELD_NUMBER = 13;
    private com.zhang.sqone.bean.Test2.ReqTest22.Test22Map a_;
    /**
     * <code>optional .ReqTest22.Test22Map a = 13;</code>
     *
     * <pre>
     *对象1
     * </pre>
     */
    public boolean hasA() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional .ReqTest22.Test22Map a = 13;</code>
     *
     * <pre>
     *对象1
     * </pre>
     */
    public com.zhang.sqone.bean.Test2.ReqTest22.Test22Map getA() {
      return a_;
    }
    /**
     * <code>optional .ReqTest22.Test22Map a = 13;</code>
     *
     * <pre>
     *对象1
     * </pre>
     */
    public com.zhang.sqone.bean.Test2.ReqTest22.Test22MapOrBuilder getAOrBuilder() {
      return a_;
    }

    private void initFields() {
      ac_ = "";
      id_ = "";
      stu_ = "";
      scd_ = "";
      msg_ = "";
      sid_ = "";
      dcode_ = "";
      p_ = "";
      a_ = com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAcBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStuBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getScdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(7, getMsgBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(8, getSidBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(11, getDcodeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(12, getPBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeMessage(13, a_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAcBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStuBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getScdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getMsgBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getSidBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getDcodeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getPBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, a_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhang.sqone.bean.Test2.ReqTest22 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhang.sqone.bean.Test2.ReqTest22 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhang.sqone.bean.Test2.ReqTest22 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhang.sqone.bean.Test2.ReqTest22 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhang.sqone.bean.Test2.ReqTest22 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhang.sqone.bean.Test2.ReqTest22 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhang.sqone.bean.Test2.ReqTest22 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhang.sqone.bean.Test2.ReqTest22 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhang.sqone.bean.Test2.ReqTest22 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhang.sqone.bean.Test2.ReqTest22 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhang.sqone.bean.Test2.ReqTest22 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReqTest22}
     *
     * <pre>
     *科室工作
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zhang.sqone.bean.Test2.ReqTest22OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhang.sqone.bean.Test2.internal_static_ReqTest22_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhang.sqone.bean.Test2.internal_static_ReqTest22_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhang.sqone.bean.Test2.ReqTest22.class, com.zhang.sqone.bean.Test2.ReqTest22.Builder.class);
      }

      // Construct using com.zhang.sqone.bean.Test2.ReqTest22.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ac_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        stu_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        scd_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        sid_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        dcode_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        p_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        if (aBuilder_ == null) {
          a_ = com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.getDefaultInstance();
        } else {
          aBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhang.sqone.bean.Test2.internal_static_ReqTest22_descriptor;
      }

      public com.zhang.sqone.bean.Test2.ReqTest22 getDefaultInstanceForType() {
        return com.zhang.sqone.bean.Test2.ReqTest22.getDefaultInstance();
      }

      public com.zhang.sqone.bean.Test2.ReqTest22 build() {
        com.zhang.sqone.bean.Test2.ReqTest22 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhang.sqone.bean.Test2.ReqTest22 buildPartial() {
        com.zhang.sqone.bean.Test2.ReqTest22 result = new com.zhang.sqone.bean.Test2.ReqTest22(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ac_ = ac_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.stu_ = stu_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.scd_ = scd_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sid_ = sid_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.dcode_ = dcode_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.p_ = p_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        if (aBuilder_ == null) {
          result.a_ = a_;
        } else {
          result.a_ = aBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhang.sqone.bean.Test2.ReqTest22) {
          return mergeFrom((com.zhang.sqone.bean.Test2.ReqTest22)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhang.sqone.bean.Test2.ReqTest22 other) {
        if (other == com.zhang.sqone.bean.Test2.ReqTest22.getDefaultInstance()) return this;
        if (other.hasAc()) {
          bitField0_ |= 0x00000001;
          ac_ = other.ac_;
          onChanged();
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000002;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasStu()) {
          bitField0_ |= 0x00000004;
          stu_ = other.stu_;
          onChanged();
        }
        if (other.hasScd()) {
          bitField0_ |= 0x00000008;
          scd_ = other.scd_;
          onChanged();
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000010;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasSid()) {
          bitField0_ |= 0x00000020;
          sid_ = other.sid_;
          onChanged();
        }
        if (other.hasDcode()) {
          bitField0_ |= 0x00000040;
          dcode_ = other.dcode_;
          onChanged();
        }
        if (other.hasP()) {
          bitField0_ |= 0x00000080;
          p_ = other.p_;
          onChanged();
        }
        if (other.hasA()) {
          mergeA(other.getA());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhang.sqone.bean.Test2.ReqTest22 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhang.sqone.bean.Test2.ReqTest22) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string ac = 1;
      private java.lang.Object ac_ = "";
      /**
       * <code>optional string ac = 1;</code>
       *
       * <pre>
       *请求标识
       * </pre>
       */
      public boolean hasAc() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string ac = 1;</code>
       *
       * <pre>
       *请求标识
       * </pre>
       */
      public java.lang.String getAc() {
        java.lang.Object ref = ac_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ac_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ac = 1;</code>
       *
       * <pre>
       *请求标识
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAcBytes() {
        java.lang.Object ref = ac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ac = 1;</code>
       *
       * <pre>
       *请求标识
       * </pre>
       */
      public Builder setAc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ac = 1;</code>
       *
       * <pre>
       *请求标识
       * </pre>
       */
      public Builder clearAc() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ac_ = getDefaultInstance().getAc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ac = 1;</code>
       *
       * <pre>
       *请求标识
       * </pre>
       */
      public Builder setAcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ac_ = value;
        onChanged();
        return this;
      }

      // optional string id = 2;
      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 2;</code>
       *
       * <pre>
       *ID
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string id = 2;</code>
       *
       * <pre>
       *ID
       * </pre>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 2;</code>
       *
       * <pre>
       *ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 2;</code>
       *
       * <pre>
       *ID
       * </pre>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 2;</code>
       *
       * <pre>
       *ID
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 2;</code>
       *
       * <pre>
       *ID
       * </pre>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }

      // optional string stu = 3;
      private java.lang.Object stu_ = "";
      /**
       * <code>optional string stu = 3;</code>
       *
       * <pre>
       *请求返回标识
       * </pre>
       */
      public boolean hasStu() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string stu = 3;</code>
       *
       * <pre>
       *请求返回标识
       * </pre>
       */
      public java.lang.String getStu() {
        java.lang.Object ref = stu_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          stu_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stu = 3;</code>
       *
       * <pre>
       *请求返回标识
       * </pre>
       */
      public com.google.protobuf.ByteString
          getStuBytes() {
        java.lang.Object ref = stu_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stu_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stu = 3;</code>
       *
       * <pre>
       *请求返回标识
       * </pre>
       */
      public Builder setStu(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stu = 3;</code>
       *
       * <pre>
       *请求返回标识
       * </pre>
       */
      public Builder clearStu() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stu_ = getDefaultInstance().getStu();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stu = 3;</code>
       *
       * <pre>
       *请求返回标识
       * </pre>
       */
      public Builder setStuBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stu_ = value;
        onChanged();
        return this;
      }

      // optional string scd = 4;
      private java.lang.Object scd_ = "";
      /**
       * <code>optional string scd = 4;</code>
       *
       * <pre>
       *请求结果标识
       * </pre>
       */
      public boolean hasScd() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string scd = 4;</code>
       *
       * <pre>
       *请求结果标识
       * </pre>
       */
      public java.lang.String getScd() {
        java.lang.Object ref = scd_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          scd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string scd = 4;</code>
       *
       * <pre>
       *请求结果标识
       * </pre>
       */
      public com.google.protobuf.ByteString
          getScdBytes() {
        java.lang.Object ref = scd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          scd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string scd = 4;</code>
       *
       * <pre>
       *请求结果标识
       * </pre>
       */
      public Builder setScd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        scd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string scd = 4;</code>
       *
       * <pre>
       *请求结果标识
       * </pre>
       */
      public Builder clearScd() {
        bitField0_ = (bitField0_ & ~0x00000008);
        scd_ = getDefaultInstance().getScd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string scd = 4;</code>
       *
       * <pre>
       *请求结果标识
       * </pre>
       */
      public Builder setScdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        scd_ = value;
        onChanged();
        return this;
      }

      // optional string msg = 7;
      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 7;</code>
       *
       * <pre>
       *请求结果消息
       * </pre>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string msg = 7;</code>
       *
       * <pre>
       *请求结果消息
       * </pre>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 7;</code>
       *
       * <pre>
       *请求结果消息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 7;</code>
       *
       * <pre>
       *请求结果消息
       * </pre>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 7;</code>
       *
       * <pre>
       *请求结果消息
       * </pre>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 7;</code>
       *
       * <pre>
       *请求结果消息
       * </pre>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msg_ = value;
        onChanged();
        return this;
      }

      // optional string sid = 8;
      private java.lang.Object sid_ = "";
      /**
       * <code>optional string sid = 8;</code>
       *
       * <pre>
       *请求的用户sid
       * </pre>
       */
      public boolean hasSid() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string sid = 8;</code>
       *
       * <pre>
       *请求的用户sid
       * </pre>
       */
      public java.lang.String getSid() {
        java.lang.Object ref = sid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sid = 8;</code>
       *
       * <pre>
       *请求的用户sid
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSidBytes() {
        java.lang.Object ref = sid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sid = 8;</code>
       *
       * <pre>
       *请求的用户sid
       * </pre>
       */
      public Builder setSid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        sid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sid = 8;</code>
       *
       * <pre>
       *请求的用户sid
       * </pre>
       */
      public Builder clearSid() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sid_ = getDefaultInstance().getSid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sid = 8;</code>
       *
       * <pre>
       *请求的用户sid
       * </pre>
       */
      public Builder setSidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        sid_ = value;
        onChanged();
        return this;
      }

      // optional string dcode = 11;
      private java.lang.Object dcode_ = "";
      /**
       * <code>optional string dcode = 11;</code>
       *
       * <pre>
       *科室code
       * </pre>
       */
      public boolean hasDcode() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string dcode = 11;</code>
       *
       * <pre>
       *科室code
       * </pre>
       */
      public java.lang.String getDcode() {
        java.lang.Object ref = dcode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          dcode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dcode = 11;</code>
       *
       * <pre>
       *科室code
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDcodeBytes() {
        java.lang.Object ref = dcode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dcode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dcode = 11;</code>
       *
       * <pre>
       *科室code
       * </pre>
       */
      public Builder setDcode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        dcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dcode = 11;</code>
       *
       * <pre>
       *科室code
       * </pre>
       */
      public Builder clearDcode() {
        bitField0_ = (bitField0_ & ~0x00000040);
        dcode_ = getDefaultInstance().getDcode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dcode = 11;</code>
       *
       * <pre>
       *科室code
       * </pre>
       */
      public Builder setDcodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        dcode_ = value;
        onChanged();
        return this;
      }

      // optional string p = 12;
      private java.lang.Object p_ = "";
      /**
       * <code>optional string p = 12;</code>
       *
       * <pre>
       *当前页数
       * </pre>
       */
      public boolean hasP() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string p = 12;</code>
       *
       * <pre>
       *当前页数
       * </pre>
       */
      public java.lang.String getP() {
        java.lang.Object ref = p_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          p_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string p = 12;</code>
       *
       * <pre>
       *当前页数
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPBytes() {
        java.lang.Object ref = p_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          p_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string p = 12;</code>
       *
       * <pre>
       *当前页数
       * </pre>
       */
      public Builder setP(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        p_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string p = 12;</code>
       *
       * <pre>
       *当前页数
       * </pre>
       */
      public Builder clearP() {
        bitField0_ = (bitField0_ & ~0x00000080);
        p_ = getDefaultInstance().getP();
        onChanged();
        return this;
      }
      /**
       * <code>optional string p = 12;</code>
       *
       * <pre>
       *当前页数
       * </pre>
       */
      public Builder setPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        p_ = value;
        onChanged();
        return this;
      }

      // optional .ReqTest22.Test22Map a = 13;
      private com.zhang.sqone.bean.Test2.ReqTest22.Test22Map a_ = com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.zhang.sqone.bean.Test2.ReqTest22.Test22Map, com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.Builder, com.zhang.sqone.bean.Test2.ReqTest22.Test22MapOrBuilder> aBuilder_;
      /**
       * <code>optional .ReqTest22.Test22Map a = 13;</code>
       *
       * <pre>
       *对象1
       * </pre>
       */
      public boolean hasA() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional .ReqTest22.Test22Map a = 13;</code>
       *
       * <pre>
       *对象1
       * </pre>
       */
      public com.zhang.sqone.bean.Test2.ReqTest22.Test22Map getA() {
        if (aBuilder_ == null) {
          return a_;
        } else {
          return aBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ReqTest22.Test22Map a = 13;</code>
       *
       * <pre>
       *对象1
       * </pre>
       */
      public Builder setA(com.zhang.sqone.bean.Test2.ReqTest22.Test22Map value) {
        if (aBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          a_ = value;
          onChanged();
        } else {
          aBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .ReqTest22.Test22Map a = 13;</code>
       *
       * <pre>
       *对象1
       * </pre>
       */
      public Builder setA(
          com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.Builder builderForValue) {
        if (aBuilder_ == null) {
          a_ = builderForValue.build();
          onChanged();
        } else {
          aBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .ReqTest22.Test22Map a = 13;</code>
       *
       * <pre>
       *对象1
       * </pre>
       */
      public Builder mergeA(com.zhang.sqone.bean.Test2.ReqTest22.Test22Map value) {
        if (aBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100) &&
              a_ != com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.getDefaultInstance()) {
            a_ =
              com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.newBuilder(a_).mergeFrom(value).buildPartial();
          } else {
            a_ = value;
          }
          onChanged();
        } else {
          aBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .ReqTest22.Test22Map a = 13;</code>
       *
       * <pre>
       *对象1
       * </pre>
       */
      public Builder clearA() {
        if (aBuilder_ == null) {
          a_ = com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.getDefaultInstance();
          onChanged();
        } else {
          aBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      /**
       * <code>optional .ReqTest22.Test22Map a = 13;</code>
       *
       * <pre>
       *对象1
       * </pre>
       */
      public com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.Builder getABuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getAFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ReqTest22.Test22Map a = 13;</code>
       *
       * <pre>
       *对象1
       * </pre>
       */
      public com.zhang.sqone.bean.Test2.ReqTest22.Test22MapOrBuilder getAOrBuilder() {
        if (aBuilder_ != null) {
          return aBuilder_.getMessageOrBuilder();
        } else {
          return a_;
        }
      }
      /**
       * <code>optional .ReqTest22.Test22Map a = 13;</code>
       *
       * <pre>
       *对象1
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.zhang.sqone.bean.Test2.ReqTest22.Test22Map, com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.Builder, com.zhang.sqone.bean.Test2.ReqTest22.Test22MapOrBuilder> 
          getAFieldBuilder() {
        if (aBuilder_ == null) {
          aBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.zhang.sqone.bean.Test2.ReqTest22.Test22Map, com.zhang.sqone.bean.Test2.ReqTest22.Test22Map.Builder, com.zhang.sqone.bean.Test2.ReqTest22.Test22MapOrBuilder>(
                  a_,
                  getParentForChildren(),
                  isClean());
          a_ = null;
        }
        return aBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ReqTest22)
    }

    static {
      defaultInstance = new ReqTest22(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ReqTest22)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqTest22_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqTest22_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqTest22_Test22Map_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqTest22_Test22Map_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013test2.proto\"\267\001\n\tReqTest22\022\n\n\002ac\030\001 \001(\t\022" +
      "\n\n\002id\030\002 \001(\t\022\013\n\003stu\030\003 \001(\t\022\013\n\003scd\030\004 \001(\t\022\013\n" +
      "\003msg\030\007 \001(\t\022\013\n\003sid\030\010 \001(\t\022\r\n\005dcode\030\013 \001(\t\022\t" +
      "\n\001p\030\014 \001(\t\022\037\n\001a\030\r \001(\0132\024.ReqTest22.Test22M" +
      "ap\032#\n\tTest22Map\022\n\n\002xm\030\001 \001(\t\022\n\n\002nl\030\002 \001(\tB" +
      "\026\n\024com.zhang.sqone.bean"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ReqTest22_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ReqTest22_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ReqTest22_descriptor,
              new java.lang.String[] { "Ac", "Id", "Stu", "Scd", "Msg", "Sid", "Dcode", "P", "A", });
          internal_static_ReqTest22_Test22Map_descriptor =
            internal_static_ReqTest22_descriptor.getNestedTypes().get(0);
          internal_static_ReqTest22_Test22Map_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ReqTest22_Test22Map_descriptor,
              new java.lang.String[] { "Xm", "Nl", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
